webapp/Controllers/TipoGeneroController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SmartAdminMvc.Database;
using SmartAdminMvc.Models.Areas;
using SmartAdminMvc.Models.Base;
using SmartAdminMvc.Models.Genero;

namespace SmartAdminMvc.Controllers
{
    [Authorize]
    public class TipoGeneroController : Controller
    {
        // GET: TipoGenero
        public ActionResult Index()
        {
            using (var dbRecursosHumanosEntities = new RecursosHumanosEntitie())
            {
                var listadoGenero = dbRecursosHumanosEntities.TipoGeneroes.Select(x => 
                new ListarGeneroViewModel
                {
                    IdGenero = x.IdTipoGenero,
                    Genero = x.Descripcion,
                    EstadoGenero = x.EstadoTipoGenero
                }).ToList();
                return View(listadoGenero);
            }
        }

        // GET: TipoGenero/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: TipoGenero/Create
        public ActionResult Create()
        {
            return PartialView(new CrearGeneroViewModel());
        }

        // POST: TipoGenero/Create
        [HttpPost]
        public JsonResult Create(CrearGeneroViewModel model)
        {
           
            try
            {
                if (!ModelState.IsValid)
                {
                    return Json(new { Estatus = false, Mensaje = "Revisar campos requeridos." },
                        JsonRequestBehavior.AllowGet);
                }

                using (var dbRecursosHumanosEntities = new RecursosHumanosEntitie())
                {

                    var nuevoGenero = new TipoGenero
                    {
                       Descripcion = model.Genero,
                       EstadoTipoGenero = true,
                        CreadoPor = User.Identity.Name,
                        ModificadoPor = User.Identity.Name,
                        FechaCreacion = DateTime.Now,
                        FechaModificado = DateTime.Now

                    };
                    dbRecursosHumanosEntities.TipoGeneroes.Add(nuevoGenero);
                    dbRecursosHumanosEntities.SaveChanges();

                    TempData["MensajeDeRespuesta"] = new RespuestaBase { Estatus = true, Mensage = "Se ha guardado de manera exitosa.", Titulo = "Tipo Generos" };
                    return Json(new { Estatus = true, Mensaje = "Se ha  guardado con exito." },
                        JsonRequestBehavior.AllowGet);

                }
            }
            catch (Exception ex)
            {

                return Json(new { Estatus = false, Mensaje = ex.Message },
                    JsonRequestBehavior.AllowGet);

            }
        }
        // GET: TipoGenero/Edit/5
        public ActionResult Edit(int id)
        {
            using (var dbRecursosHumanosEntities = new RecursosHumanosEntitie())
            {
               var query = dbRecursosHumanosEntities.TipoGeneroes.FirstOrDefault(x => x.IdTipoGenero == id);
                var modelo = new EditarGeneroViewModel
                {
                    IdGenero = query.IdTipoGenero,
                    Genero = query.Descripcion,
                
                };
                return PartialView(modelo);
            }
        }

        // POST: TipoGenero/Edit/5
        [HttpPost]
        public ActionResult Edit(EditarGeneroViewModel modelo)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return Json(new { Estatu = false, Mensaje = "Revisar campos requeridos." },
                        JsonRequestBehavior.AllowGet);
                }
                using (var dbRecursosHumanosEntities = new RecursosHumanosEntitie())
                {
                    var query = dbRecursosHumanosEntities.TipoGeneroes.FirstOrDefault(x => x.IdTipoGenero == modelo.IdGenero);
                    query.Descripcion = modelo.Genero;
                    
                    dbRecursosHumanosEntities.SaveChanges();

                    TempData["MensajeDeRespuesta"] = new RespuestaBase { Estatus = true, Mensage = "Se ha modificado con exito.", Titulo = "Tipo Generos" };
                    return Json(new { Estatu = true, Mensaje = "Se ha modificado con exito." },
                        JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new { Estatus = false, Mensaje = ex.Message },
                    JsonRequestBehavior.AllowGet);
            }
        }

        // GET: TipoGenero/Delete/5
        public ActionResult Delete(int id)
        {
            using (var dbRecursosHumanosEntities = new RecursosHumanosEntitie())
            {

                var query = dbRecursosHumanosEntities.TipoGeneroes.FirstOrDefault(x => x.IdTipoGenero == id);

                var modelo = new EditarGeneroViewModel
                {


                    EstadoGenero = query.EstadoTipoGenero = false,

                };
                dbRecursosHumanosEntities.SaveChanges();
                TempData["MensajeDeRespuesta"] = new RespuestaBase { Estatus = true, Mensage = "Se ha modificado con exito.", Titulo = "Genero" };
                return Json(new { Estatu = true, Mensaje = "Se ha modificado con exito." },
                    JsonRequestBehavior.AllowGet);

            }
        }

        // POST: TipoGenero/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

webapp/Views/TipoGenero/Create.cshtml
@model SmartAdminMvc.Models.Genero.CrearGeneroViewModel
@{
    Layout = null;
}

<form id="formularioDeGuardarGenero" class="smart-form">
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.Genero, htmlAttributes: new { @class = "control-label" })
        <div class="input">
            @Html.EditorFor(model => model.Genero, new { htmlAttributes = new { @class = "form-control", required = "required" } })
            @Html.ValidationMessageFor(model => model.Genero, "", new { @class = "text-danger" })
        </div>
    </div>

</form>


<script>
    $("#IdGenero").select2();
</script>

webapp/Views/TipoGenero/Edit.cshtml
@model SmartAdminMvc.Models.Genero.EditarGeneroViewModel


<form id="formularioDeEditarGenero" class="smart-form">
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.IdGenero)
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Genero, htmlAttributes: new { @class = "control-label" })
        <div class="input">
            @Html.EditorFor(model => model.Genero, new { htmlAttributes = new { @class = "form-control", required = "required" } })
            @Html.ValidationMessageFor(model => model.Genero, "", new { @class = "text-danger" })
        </div>
    </div>

</form>


<script>
    $("#IdGenero").select2();
</script>

webapp/Views/TipoGenero/Index.cshtml
@model IEnumerable<SmartAdminMvc.Models.Genero.ListarGeneroViewModel>

@{
    ViewBag.Title = "Index";
}
<div class="col-lg-12">
    <div class="jarviswidget jarviswidget-color-darken">
        <header role="heading">

            <div class="widget-toolbar" role="menu">

                <button type="button" id="btnmodalAgregarGenero" class="btn btn-primary">Crear  Genero</button>

            </div>
            <h2>
                <span class="widget-icon"> <i class="fa fa-table"></i> </span>
               Tipo de Generos
            </h2>

        </header>

        <div>

            <div class="widget-body no-padding">
                <table id="tablaDeGenero" class="table table-striped table-bordered table-hover" width="100%">
                    <thead>
                        <tr>
                            <th data-class="expand">@Html.DisplayNameFor(model => model.Genero)</th>
                            <th data-class="expand"> @Html.DisplayNameFor(model => model.EstadoGenero)</th>
                            <th></th>
                        </tr>
                    </thead>
                    @foreach (var item in Model)
                    {
                        <tr>
                            @*<td>
                                    @Html.DisplayFor(modelItem => item.IdEstadoC)
                                </td>*@
                            <td>
                                @Html.DisplayFor(modelItem => item.Genero)
                            </td>
                            <td>
                                @if (Convert.ToBoolean(item.EstadoGenero))
                                {
                                    <label class="label label-success"> Activo</label>
                                }
                                else
                                {
                                    <label class="label label-danger"> Inactivo</label>
                                }
                            </td>
                            <td>
                                <div class="btn-group btn-sm">
                                    <button type="button" class="btn btn-link dropdown-toggle  no-padding" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <xml data-iddicitionary="1003" data-class="Label-ML" title="1003">Actions</xml>
                                        <span class="caret"></span>
                                    </button><ul class="dropdown-menu dropdown-menu-left">
                                        <li>
                                            <a href="#" name="editarGenero" data-key="@item.IdGenero">
                                                <span class="fa fa-edit"></span> Editar
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" name="Archive" data-key="@item.IdGenero">
                                                <span class="fa fa-edit"></span> Deshabilitar
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modalEditarGenero" tabindex="-2" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="jarviswidget jarviswidget-color-darken">
            <header role="heading">
                <h2>
                    Editar Genero
                </h2>
            </header>
            <div>
                <div class="widget-body" id="bodyModalEditarGenero">

                </div>
                <div class="widget-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-primary" id="btnEditarGenero">Guardar Cambios</button>
                </div>
            </div>
        </div>
    </div><!-- /.modal-dialog -->
</div>

<div class="modal fade" id="modalAgregarGenero" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="jarviswidget jarviswidget-color-darken">
            <header role="heading">
                <h2>
                    <span class="fa fa-plus-circle"></span>
                    Nuevo Genero
                </h2>
            </header>
            <div>
                <div class="widget-body" id="bodyModalCrearGenero">

                </div>
                <div class="widget-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-primary" id="btnGuardarGenero">Guardar Genero</button>
                </div>
            </div>
        </div>
    </div><!-- /.modal-dialog -->
</div>
@section pagespecific {
    <script type="text/javascript">

        $(document).ready(function() {
            var responsiveHelper_dt_basic = undefined;
            var responsiveHelper_datatable_fixed_column = undefined;
            var responsiveHelper_datatable_col_reorder = undefined;
            var responsiveHelper_datatable_tabletools = undefined;

            var breakpointDefinition = {
                tablet: 1024,
                phone: 480
            };

            $('#tablaDeGenero').dataTable({
                "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>" +
                    "t" +
                    "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
                "autoWidth": true,
                "preDrawCallback": function() {
                    // Initialize the responsive datatables helper once.
                    if (!responsiveHelper_dt_basic) {
                        responsiveHelper_dt_basic =
                            new ResponsiveDatatablesHelper($('#tablaDeGenero'), breakpointDefinition);
                    }
                },
                "rowCallback": function(nRow) {
                    responsiveHelper_dt_basic.createExpandIcon(nRow);
                },
                "drawCallback": function(oSettings) {
                    responsiveHelper_dt_basic.respond();
                }
            });

            $("#tablaDeGenero tbody").on("click",
            "tr a[name=editarGenero]",
            function () {


                var idArea = $(this).attr("data-key");

                $.ajax({
                    url: "@Url.Action("Edit", "TipoGenero")",

                    data: { id: idArea },

                    success: function(partialView) {

                        $("#modalEditarGenero").modal().show();
                        $("#bodyModalEditarGenero").html(partialView);

                    }


                });

            });




        $("#btnmodalAgregarGenero").on("click",
            function() {

                var idArea = $(this).attr("data-key");

                $.ajax({
                    url: "@Url.Action("Create", "TipoGenero")",


                    success: function(partialView) {

                        $("#modalAgregarGenero").modal().show();
                        $("#bodyModalCrearGenero").html(partialView);

                    }


                });

            });
        });

        $("#btnGuardarGenero").on("click",
            function () {

                $.ajax({

                    url: "@Url.Action("Create", "TipoGenero")",

                    type: "POST",

                    data: $("#formularioDeGuardarGenero").serialize(),

                    success: function (jsonMessage) {

                        if (jsonMessage.Estatus) {
                       location.href = "@Url.Action("Index","TipoGenero")";
                        } else {
                            $.smallBox({
                                title: "Tipo Genero",

                                content: jsonMessage.Mensaje,

                                color: "#296191",

                                timeout: 4000

                            });
                        }

                    }

                });

            });
        $("#btnEditarGenero").on("click",
            function () {

                $.ajax({

                    url: "@Url.Action("Edit", "TipoGenero")",

                    type: "POST",

                    data: $("#formularioDeEditarGenero").serialize(),

                    success: function (jsonMessage) {

                        if (jsonMessage.Estatu) {
                            location.reload();
                        } else {
                            $.smallBox({
                                title: "Tipo Genero",

                                content: jsonMessage.Mensaje,

                                color: "#296191",

                                timeout: 4000

                            });
                        }

                    }

                });

            });
        $("#tablaDeGenero tbody").on("click",
            "tr a[name=Archive]",
            function () {
                var idArea = $(this).attr("data-key");
                var data = new $.fn.dataTable.Api("#tablaDeGenero").row($(this).closest("tr")).data();

                $.ajax({

                    url: "@Url.Action("Delete", "TipoGenero")",

                    data: { id: idArea },
                    
                    type: "GET",

                    success: function (jsonMessage) {

                        if (jsonMessage.Estatu) {
                            location.reload();
                        } else {
                            $.smallBox({
                                title: "Genero",

                                content: jsonMessage.Mensaje,

                                color: "#296191",

                                timeout: 4000

                            });
                        }

                    }

                });

            });
    </script>
}