webapp/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SmartAdminMvc.Controllers
{
    public class BaseController : Controller
    {
        [Authorize]
       
        // GET: Base
        public ActionResult Index()
        {
            return View();
        }
    }
}

webapp/Views/Shared/_CurrentUser.cshtml
<div class="login-info">
    <span>
        <a href="javascript:void(0);" id="show-shortcut" data-action="toggleShortcut">
            <img src="~/content/img/avatars/sunny.png" alt="me" class="online" />
            <span>@User.Identity.Name.ToLower()</span>
            <i class="fa fa-angle-down"></i>
        </a>
    </span>
</div>

webapp/Views/Shared/_Footer.cshtml
    <!-- PAGE FOOTER -->
<div class="page-footer">
    <div class="row">
        <div class="col-xs-12 col-sm-6">
            <span class="txt-color-white">Middleware.hn <span class="hidden-xs"> - RRHH</span> © 2018-2020</span>
        </div>

        <div class="col-xs-6 col-sm-6 text-right hidden-xs">
            <div class="txt-color-white inline-block">
                <i class="txt-color-blueLight hidden-mobile">Last account activity <i class="fa fa-clock-o"></i> <strong>52 mins ago &nbsp;</strong> </i>
                <div class="btn-group dropup">
                    @*<button class="btn btn-xs dropdown-toggle bg-color-blue txt-color-white" data-toggle="dropdown">
                        <i class="fa fa-link"></i> <span class="caret"></span>
                    </button>*@
                    @*<ul class="dropdown-menu pull-right text-left">
                        <li>
                            <div class="padding-5">
                                <p class="txt-color-darken font-sm no-margin">Download Progress</p>
                                <div class="progress progress-micro no-margin">
                                    <div class="progress-bar progress-bar-success" style="width: 50%;"></div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="padding-5">
                                <p class="txt-color-darken font-sm no-margin">Server Load</p>
                                <div class="progress progress-micro no-margin">
                                    <div class="progress-bar progress-bar-success" style="width: 20%;"></div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="padding-5">
                                <p class="txt-color-darken font-sm no-margin">Memory Load <span class="text-danger">*critical*</span></p>
                                <div class="progress progress-micro no-margin">
                                    <div class="progress-bar progress-bar-danger" style="width: 70%;"></div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="padding-5">
                                <button class="btn btn-block btn-default">refresh</button>
                            </div>
                        </li>
                    </ul>*@
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END PAGE FOOTER -->

webapp/Views/Shared/_Header.cshtml
    <!-- HEADER -->
<header id="header">
    <div id="logo-group">

        <!-- PLACE YOUR LOGO HERE -->
       
            <span id="logo" class="text-center">
                <big>
                    <b style="color: #ffffff;">Recursos Humanos</b>
                </big>
            </span>
        
        <!-- END LOGO PLACEHOLDER -->
        @if (Request.IsAuthenticated)
        {
            <!-- Note: The activity badge color changes when clicked and resets the number to 0
            Suggestion: You may want to set a flag when this happens to tick off all checked messages / notifications -->
            @*<span id="activity" class="activity-dropdown"> <i class="fa fa-user"></i> <b class="badge"> 21 </b> </span>*@

            <!-- AJAX-DROPDOWN : control this dropdown height, look and feel from the LESS variable file -->
            <div class="ajax-dropdown">

                <!-- the ID links are fetched via AJAX to the ajax container "ajax-notifications" -->
                <div class="btn-group btn-group-justified" data-toggle="buttons">
                    <label class="btn btn-default">
                        <input type="radio" name="activity" id="~/content/ajax/notify/mail.html">
                        Msgs (14)
                    </label>
                    <label class="btn btn-default">
                        <input type="radio" name="activity" id="~/content/ajax/notify/notifications.html">
                        notify (3)
                    </label>
                    <label class="btn btn-default">
                        <input type="radio" name="activity" id="~/content/ajax/notify/tasks.html">
                        Tasks (4)
                    </label>
                </div>

                <!-- notification content -->
                <div class="ajax-notifications custom-scroll">

                    <div class="alert alert-transparent">
                        <h4>Click a button to show messages here</h4>
                        This blank page message helps protect your privacy, or you can show the first message here automatically.
                    </div>

                    <i class="fa fa-lock fa-4x fa-border"></i>

                </div>
                <!-- end notification content -->
                <!-- footer: refresh area -->
                <span>
                    Last updated on: 12/12/2013 9:43AM
                    <button type="button" data-loading-text="<i class='fa fa-refresh fa-spin'></i> Loading..." class="btn btn-xs btn-default pull-right">
                        <i class="fa fa-refresh"></i>
                    </button>
                </span>
                <!-- end footer -->

            </div>
            <!-- END AJAX-DROPDOWN -->
        }
    </div>
    @if (Request.IsAuthenticated)
    {
        <!-- projects dropdown -->
        @*<div class="project-context hidden-xs">

            <span class="label">Projects:</span>
            <span class="project-selector dropdown-toggle" data-toggle="dropdown">Recent projects <i class="fa fa-angle-down"></i></span>*@

        <!-- Suggestion: populate this list with fetch and push technique -->
        @*<ul class="dropdown-menu">
                <li>
                    <a href="javascript:void(0);">Online e-merchant management system - attaching integration with the iOS</a>
                </li>
                <li>
                    <a href="javascript:void(0);">Notes on pipeline upgradee</a>
                </li>
                <li>
                    <a href="javascript:void(0);">Assesment Report for merchant account</a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="javascript:void(0);"><i class="fa fa-power-off"></i> Clear</a>
                </li>
            </ul>*@
        <!-- end dropdown-menu-->

        @*</div>*@
        <!-- end projects dropdown -->
    }
    <section id="top-right">
        @if (@Model is HelperResult)
        {
            @Model
        }
        else
        {
            <div class="pull-right">
                @Html.Partial("_TopRight")
            </div>
        }
    </section>
</header>
<!-- END HEADER -->
<div id="ribbon" style="background-color: #ffffff;">
    <a class="btn btn-link" href="@Url.Action("Index", "Base")">
        <i class="fa fa-arrow-circle-o-left fa-2x"> </i>
    </a>
</div>

webapp/Views/Shared/_Layout.cshtml
@using SmartAdminMvc.Models.Base

<!DOCTYPE html>
<html lang="en-us" id="@ViewBag.PageId" class="@Settings.CurrentTheme">
<head>
    <meta charset=" utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <title> SGRRHH </title>
    <meta name="description" content="">
    <meta name="author" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <!-- Basic Styles -->
    @Styles.Render("~/content/smartadmin")
    <!-- FAVICONS -->
    <link rel="shortcut icon" href="~/content/img/favicon/favicon.ico" type="image/x-icon">
    <link rel="icon" href="~/content/img/favicon/favicon.ico" type="image/x-icon">

    <!-- GOOGLE FONT -->
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700">

    <!-- Specifying a Webpage Icon for Web Clip
    Ref: https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html -->
    <link rel="apple-touch-icon" href="~/content/img/splash/sptouch-icon-iphone.png">
    <link rel="apple-touch-icon" sizes="76x76" href="~/content/img/splash/touch-icon-ipad.png">
    <link rel="apple-touch-icon" sizes="120x120" href="~/content/img/splash/touch-icon-iphone-retina.png">
    <link rel="apple-touch-icon" sizes="152x152" href="~/content/img/splash/touch-icon-ipad-retina.png">

    <!-- iOS web-app metas : hides Safari UI Components and Changes Status Bar Appearance -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">

    <!-- Startup image for web apps -->
    <link rel="apple-touch-startup-image" href="~/content/img/splash/ipad-landscape.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)">
    <link rel="apple-touch-startup-image" href="~/content/img/splash/ipad-portrait.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)">
    <link rel="apple-touch-startup-image" href="~/content/img/splash/iphone.png" media="screen and (max-device-width: 320px)">
</head>
<body class="smart-style-1 hidden-menu img-hcf">
        @{ Html.RenderPartial("_Header", RenderSection("topright", false)); }
        @{ Html.RenderPartialIf("_Aside", Request.IsAuthenticated); }
        <div id="main" role="main">
            @*@{ Html.RenderPartialIf("_Ribbon", Request.IsAuthenticated); }*@
            @RenderBody()
        </div>
        @if (Request.IsAuthenticated)
        {
            Html.RenderPartial("_Footer");
            Html.RenderPartialIf("_Tiles", Settings.EnableTiles);
        }
        @{ Html.RenderPartial("_Scripts", RenderSection("pagespecific", false)); }
        
    </body>
    @RenderSection("scripts", required: false)


    <script>

    $(document).ready(function() {


        @if (TempData["MensajeDeRespuesta"] != null)
    {

        var respuesta = TempData["MensajeDeRespuesta"] as RespuestaBase;

        if (respuesta.Estatus)
        {

        <text>ShowMessageSuccess("@respuesta.Titulo","@respuesta.Mensage");</text>

        }
        else
        {
        <text> $.smallBox({ title: "@respuesta.Titulo", content: "@respuesta.Mensage", color: "#296191",timeout: 8000,icon: "fa fa-remove shake animated"});</text>
        }

    }

    });


    function ShowMessageSuccess(title, message) {
        $.smallBox({ title: title, content: message, color: "#739E73", timeout: 8000});
    }

    </script>

</html>

webapp/Views/Shared/_Ribbon.cshtml
<!-- RIBBON -->
<div id="ribbon">
    <li class="">
        @* <a href="@Url.Action("Index", "Home")" title="blank_"><i class="fa fa-lg fa-fw fa-home"></i> <span class="menu-item-parent">@Html.DisplayTranslatedMessage(126)</span></a>*@
        <a href="@Url.Action("Index", "Base")" title="blank_"><i class="fa fa-lg fa-fw fa-home"></i> <span class="menu-item-parent">Inicio</span></a>
    </li>
    <span class="ribbon-button-alignment">
        <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh" rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
						<i class="fa fa-refresh"></i>
					</span>
    </span>

    <!-- breadcrumb -->
    <ol class="breadcrumb">
        <li>Home</li>
        <li>Dashboard</li>
    </ol>
    <!-- end breadcrumb -->
    <!-- You can also add more buttons to the
    ribbon for further usability

    Example below:

    <span class="ribbon-button-alignment pull-right">
    <span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
    <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
    <span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
    </span> -->

</div>
<!-- END RIBBON -->

webapp/Views/Shared/_Scripts.cshtml
<!-- Link to Google CDN's jQuery + jQueryUI; fall back to local -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script> if (!window.jQuery) { document.write('<script src="/scripts/libs/jquery-2.1.1.min.js"><\/script>'); } </script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script> if (!window.jQuery.ui) { document.write('<script src="/scripts/libs/jquery-ui-1.10.3.min.js"><\/script>'); } </script>

<!-- IMPORTANT: SmartAdmin Core -->
@Scripts.Render("~/scripts/smartadmin")

@if (Request.IsAuthenticated)
{
    <!-- PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)-->
    <script data-pace-options='{ "restartOnRequestAfter": true }' src="~/scripts/plugin/pace/pace.min.js"></script>
}

<!-- Voice command : plugin -->
<script src="~/scripts/speech/voicecommand.min.js"></script>

<!-- SmartChat UI : plugin -->
@Scripts.Render("~/scripts/smart-chat")

<!-- DataTables : plugin -->
@Scripts.Render("~/scripts/datatables")

<!-- jQGrid : plugin -->
@Scripts.Render("~/scripts/jq-grid")

<!-- Forms : plugin -->
@Scripts.Render("~/scripts/forms")

<!-- Flot Chart Plugin: Flot Engine, Flot Resizer, Flot Tooltip, Morris, Sparkline, EasyPie -->
@Scripts.Render("~/scripts/charts")

<!-- Vector Maps Plugin: Vectormap engine, Vectormap language -->
@Scripts.Render("~/scripts/vector-map")

<!-- Full Calendar -->
@Scripts.Render("~/scripts/full-calendar")

<!-- DO NOT REMOVE : GLOBAL FUNCTIONS! -->
<script>
    $(document).ready(function () {
        pageSetUp();
        drawBreadCrumb();
    });
</script>

@if (@Model is HelperResult)
{
    @Model
}
<!-- Your GOOGLE ANALYTICS CODE Below-->
    @*<script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'xx-xxxxxxxx-x']);
    _gaq.push(['_trackPageview']);

    (function () {
        var ga = document.createElement('script');
        ga.type = 'text/javascript';
        ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(ga, s);
    })();
</script>*@

webapp/Views/Shared/_Tiles.cshtml
<!-- SHORTCUT AREA : With large tiles (activated via clicking user name tag)
Note: These tiles are completely responsive,
you can add as many as you like
-->
<div id="shortcut">
    <ul>
        <li>
            <a href="@Url.Action("inbox", "home")" class="jarvismetro-tile big-cubes bg-color-blue"> <span class="iconbox"> <i class="fa fa-envelope fa-4x"></i> <span>Mail <span class="label pull-right bg-color-darken">14</span></span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("calendar", "home")" class="jarvismetro-tile big-cubes bg-color-orangeDark"> <span class="iconbox"> <i class="fa fa-calendar fa-4x"></i> <span>Calendar</span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("googlemap", "home")" class="jarvismetro-tile big-cubes bg-color-purple"> <span class="iconbox"> <i class="fa fa-map-marker fa-4x"></i> <span>Maps</span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("invoice", "misc")" class="jarvismetro-tile big-cubes bg-color-blueDark"> <span class="iconbox"> <i class="fa fa-book fa-4x"></i> <span>Invoice <span class="label pull-right bg-color-darken">99</span></span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("gallery", "appviews")" class="jarvismetro-tile big-cubes bg-color-greenLight"> <span class="iconbox"> <i class="fa fa-picture-o fa-4x"></i> <span>Gallery </span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("profile", "appviews")" class="jarvismetro-tile big-cubes selected bg-color-pinkDark"> <span class="iconbox"> <i class="fa fa-user fa-4x"></i> <span>My Profile </span> </span> </a>
        </li>
    </ul>
</div>
<!-- END SHORTCUT AREA -->

webapp/Views/Shared/_TopRight.cshtml
<!-- collapse menu button -->
@*<div id="hide-menu" class="btn-header pull-right">
    <span> <a href="javascript:void(0);" data-action="toggleMenu" title="Collapse Menu"><i class="fa fa-reorder"></i></a> </span>
</div>*@
<!-- end collapse menu -->
<!-- #MOBILE -->
<!-- Top menu profile link : this shows only when top menu is active -->
@*<ul id="mobile-profile-img" class="header-dropdown-list hidden-xs padding-5">
    <li class="">
        <a href="#" class="dropdown-toggle no-margin userdropdown" data-toggle="dropdown">
            <img src="~/content/img/avatars/sunny.png" alt="John Doe" class="online" />
        </a>
        <ul class="dropdown-menu pull-right">
            <li>
                <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0"><i class="fa fa-cog"></i> Setting</a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#" class="padding-10 padding-top-0 padding-bottom-0"> <i class="fa fa-user"></i> Profile</a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0" data-action="toggleShortcut"><i class="fa fa-arrow-down"></i> <>S</>hortcut</a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0" data-action="launchFullscreen"><i class="fa fa-arrows-alt"></i> Full <>S</>creen</a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="@Url.Action("login", "account")" class="padding-10 padding-top-5 padding-bottom-5" data-action="userLogout"><i class="fa fa-sign-out fa-lg"></i> <strong><>L</>ogout</strong></a>
            </li>
        </ul>
    </li>
</ul>*@

<!-- logout button -->
<div id="logout" class="btn-header transparent pull-right">
    <span> <a href="@Url.Action("login", "account")" title="Sign Out" data-action="userLogout" data-logout-msg="You can improve your security further after logging out by closing this opened browser"><i class="fa fa-sign-out"></i></a> </span>
</div>
<!-- end logout button -->
<!-- search mobile button (this is hidden till mobile view port) -->

<!-- end search mobile button -->
<!-- input: search field -->

<!-- end input: search field -->
<!-- fullscreen button -->

<!-- end fullscreen button -->
<!-- #Voice Command: Start Speech -->
<
<!-- end voice command -->
<!-- multiple lang dropdown : find all flags in the flags page -->
<ul class="header-dropdown-list hidden-xs">
    <li>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <img src="~/content/img/blank.gif" class="flag flag-us" alt="United States"> <span> English (US) </span> <i class="fa fa-angle-down"></i> </a>
        <ul class="dropdown-menu pull-right">
            <li class="active">
                <a href="javascript:void(0);"><img src="~/content/img/blank.gif" class="flag flag-us" alt="United States"> English (US)</a>
            </li>
            <li>
                <a href="javascript:void(0);"><img src="~/content/img/blank.gif" class="flag flag-fr" alt="France"> Français</a>
            </li>
            <li>
                <a href="javascript:void(0);"><img src="~/content/img/blank.gif" class="flag flag-es" alt="Spanish"> Español</a>
            </li>
            <li>
                <a href="javascript:void(0);"><img src="~/content/img/blank.gif" class="flag flag-de" alt="German"> Deutsch</a>
            </li>
            <li>
                <a href="javascript:void(0);"><img src="~/content/img/blank.gif" class="flag flag-jp" alt="Japan"> 日本語</a>
            </li>
            <li>
                <a href="javascript:void(0);"><img src="~/content/img/blank.gif" class="flag flag-cn" alt="China"> 中文</a>
            </li>
            <li>
                <a href="javascript:void(0);"><img src="~/content/img/blank.gif" class="flag flag-it" alt="Italy"> Italiano</a>
            </li>
            <li>
                <a href="javascript:void(0);"><img src="~/content/img/blank.gif" class="flag flag-pt" alt="Portugal"> Portugal</a>
            </li>
            <li>
                <a href="javascript:void(0);"><img src="~/content/img/blank.gif" class="flag flag-ru" alt="Russia"> Русский язык</a>
            </li>
            <li>
                <a href="javascript:void(0);"><img src="~/content/img/blank.gif" class="flag flag-kr" alt="Korea"> 한국어</a>
            </li>

        </ul>
    </li>
</ul>
<!-- end multiple lang -->