webapp/Models/TipoPersona/CreaeTipoPersonaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SmartAdminMvc.Models.TipoPersona
{
    public class CreaeTipoPersonaViewModel
    {
        public string Nombre { get; set; }
    }
}

webapp/Models/TipoPersona/EditarPersonaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SmartAdminMvc.Models.TipoPersona
{
    public class EditarPersonaViewModel : CreaeTipoPersonaViewModel
    {
        public int idTipoPersona { get; set; }
        public bool Estado { get; set; }
    }
}

webapp/Models/TipoPersona/TipoPersonaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SmartAdminMvc.Models.TipoPersona
{
    public class TipoPersonaViewModel :EditarPersonaViewModel
    {
       
     
    }
}

webapp/Controllers/TipoPersonaController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SmartAdminMvc.Database;
using SmartAdminMvc.Models.Base;
using SmartAdminMvc.Models.TipoPersona;


namespace SmartAdminMvc.Controllers
{
    [Authorize]
    public class TipoPersonaController : Controller
    {
        // GET: TipoPersona
        public ActionResult Index()
        {
            using (var dbRecursosHumanosEntities = new RecursosHumanosEntitie())
            {
                var listadoTipoPlanilla = dbRecursosHumanosEntities.TipoPersonas.Select(x => new TipoPersonaViewModel { idTipoPersona = x.IdTipoPersona, Nombre= x.Descripcion, Estado = x.EstadoTipoPersona }).ToList();
                return View(listadoTipoPlanilla);
            }
        }

        // GET: TipoPersona/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: TipoPersona/Create
        public ActionResult Create()
        {
            return PartialView(new CreaeTipoPersonaViewModel());
        }

        // POST: TipoPersona/Create
        [HttpPost]
        public JsonResult Create(CreaeTipoPersonaViewModel modelo)
        {

            try
            {
                if (!ModelState.IsValid)
                {
                    return Json(new { Estatus = false, Mensaje = "Revisar campos requeridos." },
                        JsonRequestBehavior.AllowGet);
                }

                using (var dbRecursosHumanosEntities = new RecursosHumanosEntitie())
                {
                    var nuevoTp = new TipoPersona()
                    {
                        Descripcion = modelo.Nombre,
                        EstadoTipoPersona = true,
                        CreadoPor = User.Identity.Name,
                        ModificadoPor = User.Identity.Name,
                        FechaCreacion = DateTime.Now,
                        FechaModificado = DateTime.Now

                    };
                    dbRecursosHumanosEntities.TipoPersonas.Add(nuevoTp);
                    dbRecursosHumanosEntities.SaveChanges();

                    TempData["MensajeDeRespuesta"] = new RespuestaBase { Estatus = true, Mensage = "Se ha guardado de manera exitosa.", Titulo = "Tipo Persona" };
                    return Json(new { Estatus = true, Mensaje = "Se ha  guardado con exito." },
                        JsonRequestBehavior.AllowGet);

                }
            }
            catch (Exception ex)
            {

                return Json(new { Estatus = false, Mensaje = ex.Message },
                    JsonRequestBehavior.AllowGet);

            }
        }

        // GET: TipoPersona/Edit/5
        public ActionResult Edit(int id)
        {
            using (var dbRecursosHumanosEntities = new RecursosHumanosEntitie())
            {
                var query = dbRecursosHumanosEntities.TipoPersonas.FirstOrDefault(x => x.IdTipoPersona == id);
                var modelo = new EditarPersonaViewModel
                {
                    idTipoPersona = query.IdTipoPersona,
                    Nombre= query.Descripcion,

                };
                return PartialView(modelo);
            }
        }

        // POST: TipoPersona/Edit/5
        [HttpPost]
        public ActionResult Edit(EditarPersonaViewModel modelo)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return Json(new { Estatu = false, Mensaje = "Revisar campos requeridos." },
                        JsonRequestBehavior.AllowGet);
                }
                using (var dbRecursosHumanosEntities = new RecursosHumanosEntitie())
                {
                    var query = dbRecursosHumanosEntities.TipoPersonas.FirstOrDefault(x => x.IdTipoPersona == modelo.idTipoPersona);
                    query.Descripcion = modelo.Nombre;

                    dbRecursosHumanosEntities.SaveChanges();

                    TempData["MensajeDeRespuesta"] = new RespuestaBase { Estatus = true, Mensage = "Se ha modificado con exito.", Titulo = "Tipo Persona" };
                    return Json(new { Estatu = true, Mensaje = "Se ha modificado con exito." },
                        JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new { Estatus = false, Mensaje = ex.Message },
                    JsonRequestBehavior.AllowGet);
            }
        }

        // GET: TipoPersona/Delete/5
        public ActionResult Delete(int id)
        {
            using (var dbRecursosHumanosEntities = new RecursosHumanosEntitie())
            {

                var query = dbRecursosHumanosEntities.TipoPersonas.FirstOrDefault(x => x.IdTipoPersona == id);

                var modelo = new EditarPersonaViewModel
                {


                    Estado = query.EstadoTipoPersona = false,

                };
                dbRecursosHumanosEntities.SaveChanges();
                TempData["MensajeDeRespuesta"] = new RespuestaBase { Estatus = true, Mensage = "Se ha modificado con exito.", Titulo = "Tipo Persona" };
                return Json(new { Estatu = true, Mensaje = "Se ha modificado con exito." },
                    JsonRequestBehavior.AllowGet);

            }
        }

        // POST: TipoPersona/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

webapp/Views/TipoPersona/Create.cshtml
@model SmartAdminMvc.Models.TipoPersona.CreaeTipoPersonaViewModel
@{
    Layout = null;
}

<form id="formularioDeGuardarPersona" class="smart-form">
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label" })
        <div class="input">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", required = "required" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

</form>


<script>
    $("#IdPersona").select2();
</script>

webapp/Views/TipoPersona/Edit.cshtml
@model SmartAdminMvc.Models.TipoPersona.EditarPersonaViewModel


<form id="formularioDeEditarPersona" class="smart-form">
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.idTipoPersona)
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label" })
        <div class="input">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", required = "required" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

</form>


<script>
    $("#IdPersona").select2();
</script>

webapp/Views/TipoPersona/Index.cshtml
@model IEnumerable<SmartAdminMvc.Models.TipoPersona.TipoPersonaViewModel>

@{
    ViewBag.Title = "Index";
}
<div class="col-lg-12">
    <div class="jarviswidget jarviswidget-color-darken">
        <header role="heading">

            <div class="widget-toolbar" role="menu">

                <button type="button" id="btnmodalAgregarPersona" class="btn btn-primary">Crear  Tipo Persona</button>

            </div>
            <h2>
                <span class="widget-icon"> <i class="fa fa-table"></i> </span>
                Tipo Persona
            </h2>

        </header>

        <div>

            <div class="widget-body no-padding">
                <table id="tablaDePersona" class="table table-striped table-bordered table-hover" width="100%">
                    <thead>
                        <tr>
                            <th data-class="expand"> @Html.DisplayNameFor(model => model.Nombre)</th>
                            <th data-class="expand"> @Html.DisplayNameFor(model => model.Estado)</th>
                            <th></th>
                        </tr>
                    </thead>
                    @foreach (var item in Model)
                    {
                        <tr>
                            @*<td>
                                    @Html.DisplayFor(modelItem => item.IdEstadoC)
                                </td>*@
                            <td>
                                @Html.DisplayFor(modelItem => item.Nombre)
                            </td>
                            <td>
                                @if (Convert.ToBoolean(item.Estado))
                                {
                                    <label class="label label-success"> Activo</label>
                                }
                                else
                                {
                                    <label class="label label-danger"> Inactivo</label>
                                }
                            </td>
                            <td>
                                <div class="btn-group btn-sm">
                                    <button type="button" class="btn btn-link dropdown-toggle  no-padding" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <xml data-iddicitionary="1003" data-class="Label-ML" title="1003">Actions</xml>
                                        <span class="caret"></span>
                                    </button><ul class="dropdown-menu dropdown-menu-left">
                                        <li>
                                            <a href="#" name="editarPersona" data-key="@item.idTipoPersona">
                                                <span class="fa fa-edit"></span> Editar
                                            </a>
                                        </li>
                                    
                                        <li>
                                            <a href="#" name="Archive" data-key="@item.idTipoPersona">
                                                <span class="fa fa-edit"></span> Deshabilitar
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modalEditarPersona" tabindex="-2" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="jarviswidget jarviswidget-color-darken">
            <header role="heading">
                <h2>
                    Editar Tipo Persona
                </h2>
            </header>
            <div>
                <div class="widget-body" id="bodyModalEditarPersona">

                </div>
                <div class="widget-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-primary" id="btnEditarPersona">Guardar Cambios</button>
                </div>
            </div>
        </div>
    </div><!-- /.modal-dialog -->
</div>

<div class="modal fade" id="modalAgregarPersona" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="jarviswidget jarviswidget-color-darken">
            <header role="heading">
                <h2>
                    <span class="fa fa-plus-circle"></span>
                    Nuevo Tipo Persona
                </h2>
            </header>
            <div>
                <div class="widget-body" id="bodyModalCrearPersona">

                </div>
                <div class="widget-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-primary" id="btnGuardarPersona">Guardar Persona</button>
                </div>
            </div>
        </div>
    </div><!-- /.modal-dialog -->
</div>
@section pagespecific {
    <script type="text/javascript">

        $(document).ready(function() {
            var responsiveHelper_dt_basic = undefined;
            var responsiveHelper_datatable_fixed_column = undefined;
            var responsiveHelper_datatable_col_reorder = undefined;
            var responsiveHelper_datatable_tabletools = undefined;

            var breakpointDefinition = {
                tablet: 1024,
                phone: 480
            };

            $('#tablaDePersona').dataTable({
                "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>" +
                    "t" +
                    "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
                "autoWidth": true,
                "preDrawCallback": function() {
                    // Initialize the responsive datatables helper once.
                    if (!responsiveHelper_dt_basic) {
                        responsiveHelper_dt_basic =
                            new ResponsiveDatatablesHelper($('#tablaDePersona'), breakpointDefinition);
                    }
                },
                "rowCallback": function(nRow) {
                    responsiveHelper_dt_basic.createExpandIcon(nRow);
                },
                "drawCallback": function(oSettings) {
                    responsiveHelper_dt_basic.respond();
                }
            });

            $("#tablaDePersona tbody").on("click",
            "tr a[name=editarPersona]",
            function () {


                var idArea = $(this).attr("data-key");

                $.ajax({
                    url: "@Url.Action("Edit", "TipoPersona")",

                    data: { id: idArea },

                    success: function(partialView) {

                        $("#modalEditarPersona").modal().show();
                        $("#bodyModalEditarPersona").html(partialView);

                    }


                });

            });




            $("#btnmodalAgregarPersona").on("click",
            function() {

                var idArea = $(this).attr("data-key");

                $.ajax({
                    url: "@Url.Action("Create", "TipoPersona")",


                    success: function(partialView) {

                        $("#modalAgregarPersona").modal().show();
                        $("#bodyModalCrearPersona").html(partialView);

                    }


                });

            });
        });

        $("#btnGuardarPersona").on("click",
            function () {

                $.ajax({

                    url: "@Url.Action("Create", "TipoPersona")",

                    type: "POST",

                    data: $("#formularioDeGuardarPersona").serialize(),

                    success: function (jsonMessage) {

                        if (jsonMessage.Estatus) {
                       location.href = "@Url.Action("Index", "TipoPersona")";
                        } else {
                            $.smallBox({
                                title: "Tipo Persona",

                                content: jsonMessage.Mensaje,

                                color: "#296191",

                                timeout: 4000

                            });
                        }

                    }

                });

            });
        $("#btnEditarPersona").on("click",
            function () {

                $.ajax({

                    url: "@Url.Action("Edit", "TipoPersona")",

                    type: "POST",

                    data: $("#formularioDeEditarPersona").serialize(),

                    success: function (jsonMessage) {

                        if (jsonMessage.Estatu) {
                            location.reload();
                        } else {
                            $.smallBox({
                                title: "Tipo Persona",

                                content: jsonMessage.Mensaje,

                                color: "#296191",

                                timeout: 4000

                            });
                        }

                    }

                });

            });
        $("#tablaDePersona tbody").on("click",
            "tr a[name=Archive]",
            function () {
                var idArea = $(this).attr("data-key");
                var data = new $.fn.dataTable.Api("#tablaDePersona").row($(this).closest("tr")).data();

                $.ajax({

                    url: "@Url.Action("Delete", "TipoPersona")",

                    data: { id: idArea },
                    
                    type: "GET",

                    success: function (jsonMessage) {

                        if (jsonMessage.Estatu) {
                            location.reload();
                        } else {
                            $.smallBox({
                                title: "Tipo Persona",

                                content: jsonMessage.Mensaje,

                                color: "#296191",

                                timeout: 4000

                            });
                        }

                    }

                });

            });
    </script>
}