webapp/Models/TipoPlanilla/CrearTipoPlanillaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SmartAdminMvc.Models.TipoPlanilla
{
    public class CrearTipoPlanillaViewModel
    {
        public string Nombre { get; set; }
    }
}

webapp/Models/TipoPlanilla/EditarTipoPlanillaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SmartAdminMvc.Models.TipoPlanilla
{
    public class EditarTipoPlanillaViewModel : CrearTipoPlanillaViewModel
    {
        public int idTipoPlanilla { get; set; }

        public bool Estado { get; set; }
    }
}

webapp/Models/TipoPlanilla/ListarTipoPlanillaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SmartAdminMvc.Models.TipoPlanilla
{
    public class ListarTipoPlanillaViewModel : EditarTipoPlanillaViewModel
    {
 
    }
}

webapp/Controllers/TipoPlanillaController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SmartAdminMvc.Database;
using SmartAdminMvc.Models.Base;
using SmartAdminMvc.Models.Genero;
using SmartAdminMvc.Models.TipoPlanilla;
using SmartAdminMvc.Models.Turno;

namespace SmartAdminMvc.Controllers
{
    [Authorize]
    public class TipoPlanillaController : Controller
    {
        // GET: TipoPlanilla
        public ActionResult Index()
        {
            using (var dbRecursosHumanosEntities = new RecursosHumanosEntitie())
            {
                var listadoTipoPlanilla = dbRecursosHumanosEntities.TipoPlanillas.Select(x => new ListarTipoPlanillaViewModel { idTipoPlanilla = x.IdTipoPlanilla, Nombre = x.Descripcion, Estado = x.EstadoTipoPlanilla }).ToList();
                return View(listadoTipoPlanilla);
            }
        }

        // GET: TipoPlanilla/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: TipoPlanilla/Create
        public ActionResult Create()
        {
            return PartialView(new CrearTipoPlanillaViewModel());
        }

        // POST: TipoPlanilla/Create
        [HttpPost]
        public JsonResult Create(CrearTipoPlanillaViewModel modelo)
        {

            try
            {
                if (!ModelState.IsValid)
                {
                    return Json(new { Estatus = false, Mensaje = "Revisar campos requeridos." },
                        JsonRequestBehavior.AllowGet);
                }

                using (var dbRecursosHumanosEntities = new RecursosHumanosEntitie())
                {
                    var nuevoPla = new TipoPlanilla
                    {
                        Descripcion = modelo.Nombre,
                        EstadoTipoPlanilla = true,
                        CreadoPor = User.Identity.Name,
                        ModificadoPor = User.Identity.Name,
                        FechaCreacion = DateTime.Now,
                        FechaModificado = DateTime.Now

                    };
                    dbRecursosHumanosEntities.TipoPlanillas.Add(nuevoPla);
                    dbRecursosHumanosEntities.SaveChanges();

                    TempData["MensajeDeRespuesta"] = new RespuestaBase { Estatus = true, Mensage = "Se ha guardado de manera exitosa.", Titulo = "Tipo Planilla" };
                    return Json(new { Estatus = true, Mensaje = "Se ha  guardado con exito." },
                        JsonRequestBehavior.AllowGet);


                }
            }
            catch (Exception ex)
            {

                return Json(new { Estatus = false, Mensaje = ex.Message },
                    JsonRequestBehavior.AllowGet);

            }
        }
        // GET: TipoPlanilla/Edit/5
        public ActionResult Edit(int id)
        {
            using (var dbRecursosHumanosEntities = new RecursosHumanosEntitie())
            {
                var query = dbRecursosHumanosEntities.TipoPlanillas.FirstOrDefault(x => x.IdTipoPlanilla == id);
                var modelo = new EditarTipoPlanillaViewModel
                {
                    idTipoPlanilla = query.IdTipoPlanilla,
                    Nombre = query.Descripcion,

                };
                return PartialView(modelo);
            }
        }

        // POST: TipoPlanilla/Edit/5
        [HttpPost]
        public ActionResult Edit(EditarTipoPlanillaViewModel modelo)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return Json(new { Estatu = false, Mensaje = "Revisar campos requeridos." },
                        JsonRequestBehavior.AllowGet);
                }
                using (var dbRecursosHumanosEntities = new RecursosHumanosEntitie())
                {
                    var query = dbRecursosHumanosEntities.TipoPlanillas.FirstOrDefault(x => x.IdTipoPlanilla == modelo.idTipoPlanilla);
                    query.Descripcion = modelo.Nombre;

                    dbRecursosHumanosEntities.SaveChanges();

                    TempData["MensajeDeRespuesta"] = new RespuestaBase { Estatus = true, Mensage = "Se ha modificado con exito.", Titulo = "Tipo Planilla" };
                    return Json(new { Estatu = true, Mensaje = "Se ha modificado con exito." },
                        JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new { Estatus = false, Mensaje = ex.Message },
                    JsonRequestBehavior.AllowGet);
            }
        }

        // GET: TipoPlanilla/Delete/5
        public ActionResult Delete(int id)
        {
            using (var dbRecursosHumanosEntities = new RecursosHumanosEntitie())
            {

                var query = dbRecursosHumanosEntities.TipoPlanillas.FirstOrDefault(x => x.IdTipoPlanilla == id);

                var modelo = new EditarTipoPlanillaViewModel
                {


                    Estado = query.EstadoTipoPlanilla = false,

                };
                dbRecursosHumanosEntities.SaveChanges();
                TempData["MensajeDeRespuesta"] = new RespuestaBase { Estatus = true, Mensage = "Se ha modificado con exito.", Titulo = "Tipo Planilla" };
                return Json(new { Estatu = true, Mensaje = "Se ha modificado con exito." },
                    JsonRequestBehavior.AllowGet);

            }
        }

        // POST: TipoPlanilla/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

webapp/Views/TipoPlanilla/Create.cshtml
@model SmartAdminMvc.Models.TipoPlanilla.CrearTipoPlanillaViewModel
@{
    Layout = null;
}

<form id="formularioDeGuardarPlanilla" class="smart-form">
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label" })
        <div class="input">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", required = "required" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

</form>


<script>
    $("#IdPlanilla").select2();
</script>

webapp/Views/TipoPlanilla/Edit.cshtml
@model SmartAdminMvc.Models.TipoPlanilla.EditarTipoPlanillaViewModel


<form id="formularioDeEditarPlanilla" class="smart-form">
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.idTipoPlanilla)
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label" })
        <div class="input">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", required = "required" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

</form>


<script>
    $("#IdPlanilla").select2();
</script>

webapp/Views/TipoPlanilla/Index.cshtml
@model IEnumerable<SmartAdminMvc.Models.TipoPlanilla.ListarTipoPlanillaViewModel>

@{
    ViewBag.Title = "Index";
}
<div class="col-lg-12">
    <div class="jarviswidget jarviswidget-color-darken">
        <header role="heading">

            <div class="widget-toolbar" role="menu">

                <button type="button" id="btnmodalAgregarPlanilla" class="btn btn-primary">Crear  Tipo Planilla</button>

            </div>
            <h2>
                <span class="widget-icon"> <i class="fa fa-table"></i> </span>
              Tipo Planilla
            </h2>

        </header>

        <div>

            <div class="widget-body no-padding">
                <table id="tablaDePlanilla" class="table table-striped table-bordered table-hover" width="100%">
                    <thead>
                        <tr>
                            <th data-class="expand"> @Html.DisplayNameFor(model => model.Nombre)</th>
                            <th data-class="expand"> @Html.DisplayNameFor(model => model.Estado)</th>
                            <th></th>
                        </tr>
                    </thead>
                    @foreach (var item in Model)
                    {
                        <tr>
                            @*<td>
                                    @Html.DisplayFor(modelItem => item.IdEstadoC)
                                </td>*@
                            <td>
                                @Html.DisplayFor(modelItem => item.Nombre)
                            </td>
                            <td>
                                @if (Convert.ToBoolean(item.Estado))
                                {
                                    <label class="label label-success"> Activo</label>
                                }
                                else
                                {
                                    <label class="label label-danger"> Inactivo</label>
                                }
                            </td>
                            <td>
                                <div class="btn-group btn-sm">
                                    <button type="button" class="btn btn-link dropdown-toggle  no-padding" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <xml data-iddicitionary="1003" data-class="Label-ML" title="1003">Actions</xml>
                                        <span class="caret"></span>
                                    </button><ul class="dropdown-menu dropdown-menu-left">
                                        <li>
                                            <a href="#" name="editarPlanilla" data-key="@item.idTipoPlanilla">
                                                <span class="fa fa-edit"></span> Editar
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" name="Archive" data-key="@item.idTipoPlanilla">
                                                <span class="fa fa-edit"></span> Deshabilitar
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modalEditarPlanilla" tabindex="-2" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="jarviswidget jarviswidget-color-darken">
            <header role="heading">
                <h2>
                    Editar Tipo Planilla
                </h2>
            </header>
            <div>
                <div class="widget-body" id="bodyModalEditarPlanilla">

                </div>
                <div class="widget-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-primary" id="btnEditarPlanilla">Guardar Cambios</button>
                </div>
            </div>
        </div>
    </div><!-- /.modal-dialog -->
</div>

<div class="modal fade" id="modalAgregarPlanilla" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="jarviswidget jarviswidget-color-darken">
            <header role="heading">
                <h2>
                    <span class="fa fa-plus-circle"></span>
                    Nuevo Tipo Planilla
                </h2>
            </header>
            <div>
                <div class="widget-body" id="bodyModalCrearPlanilla">

                </div>
                <div class="widget-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-primary" id="btnGuardarPlanilla">Guardar Idioma</button>
                </div>
            </div>
        </div>
    </div><!-- /.modal-dialog -->
</div>
@section pagespecific {
    <script type="text/javascript">

        $(document).ready(function() {
            var responsiveHelper_dt_basic = undefined;
            var responsiveHelper_datatable_fixed_column = undefined;
            var responsiveHelper_datatable_col_reorder = undefined;
            var responsiveHelper_datatable_tabletools = undefined;

            var breakpointDefinition = {
                tablet: 1024,
                phone: 480
            };

            $('#tablaDePlanilla').dataTable({
                "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>" +
                    "t" +
                    "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
                "autoWidth": true,
                "preDrawCallback": function() {
                    // Initialize the responsive datatables helper once.
                    if (!responsiveHelper_dt_basic) {
                        responsiveHelper_dt_basic =
                            new ResponsiveDatatablesHelper($('#tablaDePlanilla'), breakpointDefinition);
                    }
                },
                "rowCallback": function(nRow) {
                    responsiveHelper_dt_basic.createExpandIcon(nRow);
                },
                "drawCallback": function(oSettings) {
                    responsiveHelper_dt_basic.respond();
                }
            });

            $("#tablaDePlanilla tbody").on("click",
            "tr a[name=editarPlanilla]",
            function () {


                var idArea = $(this).attr("data-key");

                $.ajax({
                    url: "@Url.Action("Edit", "TipoPlanilla")",

                    data: { id: idArea },

                    success: function(partialView) {

                        $("#modalEditarPlanilla").modal().show();
                        $("#bodyModalEditarPlanilla").html(partialView);

                    }


                });

            });




            $("#btnmodalAgregarPlanilla").on("click",
            function() {

                var idArea = $(this).attr("data-key");

                $.ajax({
                    url: "@Url.Action("Create", "TipoPlanilla")",


                    success: function(partialView) {

                        $("#modalAgregarPlanilla").modal().show();
                        $("#bodyModalCrearPlanilla").html(partialView);

                    }


                });

            });
        });

        $("#btnGuardarPlanilla").on("click",
            function () {

                $.ajax({

                    url: "@Url.Action("Create", "TipoPlanilla")",

                    type: "POST",

                    data: $("#formularioDeGuardarPlanilla").serialize(),

                    success: function (jsonMessage) {

                        if (jsonMessage.Estatus) {
                       location.href = "@Url.Action("Index", "TipoPlanilla")";
                        } else {
                            $.smallBox({
                                title: "ITipo Planilla",

                                content: jsonMessage.Mensaje,

                                color: "#296191",

                                timeout: 4000

                            });
                        }

                    }

                });

            });
        $("#btnEditarPlanilla").on("click",
            function () {

                $.ajax({

                    url: "@Url.Action("Edit", "TipoPlanilla")",

                    type: "POST",

                    data: $("#formularioDeEditarPlanilla").serialize(),

                    success: function (jsonMessage) {

                        if (jsonMessage.Estatu) {
                            location.reload();
                        } else {
                            $.smallBox({
                                title: "Tipo Planilla",

                                content: jsonMessage.Mensaje,

                                color: "#296191",

                                timeout: 4000

                            });
                        }

                    }

                });

            });
        $("#tablaDePlanilla tbody").on("click",
            "tr a[name=Archive]",
            function () {
                var idArea = $(this).attr("data-key");
                var data = new $.fn.dataTable.Api("#tablaDePlanilla").row($(this).closest("tr")).data();

                $.ajax({

                    url: "@Url.Action("Delete", "TipoPlanilla")",

                    data: { id: idArea },
                    
                    type: "GET",

                    success: function (jsonMessage) {

                        if (jsonMessage.Estatu) {
                            location.reload();
                        } else {
                            $.smallBox({
                                title: "Tipo Planilla",

                                content: jsonMessage.Mensaje,

                                color: "#296191",

                                timeout: 4000

                            });
                        }

                    }

                });

            });
    </script>
}